apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory-service
    spec:
      containers:
        - name: inventory
          image: lushop/inventory:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8014
              name: http
            - containerPort: 50054
              name: grpc
          volumeMounts:
            - name: config
              mountPath: /data/conf
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 50054
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 50054
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: inventory-config

