apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  ports:
    - name: http
      port: 8014
      targetPort: 8014
    - name: grpc
      port: 50054
      targetPort: 50054
  selector:
    app.kubernetes.io/name: inventory-service

