apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  config.yaml: |
    nacos:
      addr: nacos
      port: 8848
      namespaceId: de9c6a0e-1fbc-425d-8d3b-09066fea6889
      dataId: order.yaml
      groupId: lushop_grpc
    registry:
      consul:
        address: consul:8500
        scheme: http

