// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: userauth/v1/user_auth.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserAuth_GetCaptcha_FullMethodName     = "/lushop.userauth.v1.UserAuth/GetCaptcha"
	UserAuth_VerifyCaptcha_FullMethodName  = "/lushop.userauth.v1.UserAuth/VerifyCaptcha"
	UserAuth_SendSms_FullMethodName        = "/lushop.userauth.v1.UserAuth/SendSms"
	UserAuth_VerifySms_FullMethodName      = "/lushop.userauth.v1.UserAuth/VerifySms"
	UserAuth_IssueToken_FullMethodName     = "/lushop.userauth.v1.UserAuth/IssueToken"
	UserAuth_RefreshToken_FullMethodName   = "/lushop.userauth.v1.UserAuth/RefreshToken"
	UserAuth_RevokeToken_FullMethodName    = "/lushop.userauth.v1.UserAuth/RevokeToken"
	UserAuth_AddToBlacklist_FullMethodName = "/lushop.userauth.v1.UserAuth/AddToBlacklist"
	UserAuth_CheckBlacklist_FullMethodName = "/lushop.userauth.v1.UserAuth/CheckBlacklist"
)

// UserAuthClient is the client API for UserAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 用户认证服务 - 统一治理 Token/验证码/SMS/黑名单
type UserAuthClient interface {
	// ========== 验证码相关 ==========
	// 获取图形验证码
	GetCaptcha(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CaptchaReply, error)
	// 校验图形验证码（内部使用，不对外暴露 HTTP）
	VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...grpc.CallOption) (*VerifyCaptchaReply, error)
	// ========== 短信相关 ==========
	// 发送短信验证码
	SendSms(ctx context.Context, in *SendSmsReq, opts ...grpc.CallOption) (*SendSmsReply, error)
	// 校验短信验证码（内部使用）
	VerifySms(ctx context.Context, in *VerifySmsReq, opts ...grpc.CallOption) (*VerifySmsReply, error)
	// ========== Token 管理 ==========
	// 签发 Token（用于登录成功后）
	IssueToken(ctx context.Context, in *IssueTokenReq, opts ...grpc.CallOption) (*TokenReply, error)
	// 刷新 Token
	RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*TokenReply, error)
	// 撤销 Token（登出）
	RevokeToken(ctx context.Context, in *RevokeTokenReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ========== 黑名单管理 ==========
	// 添加到黑名单（内部使用）
	AddToBlacklist(ctx context.Context, in *AddToBlacklistReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 检查是否在黑名单（内部使用）
	CheckBlacklist(ctx context.Context, in *CheckBlacklistReq, opts ...grpc.CallOption) (*CheckBlacklistReply, error)
}

type userAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAuthClient(cc grpc.ClientConnInterface) UserAuthClient {
	return &userAuthClient{cc}
}

func (c *userAuthClient) GetCaptcha(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CaptchaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptchaReply)
	err := c.cc.Invoke(ctx, UserAuth_GetCaptcha_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthClient) VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...grpc.CallOption) (*VerifyCaptchaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCaptchaReply)
	err := c.cc.Invoke(ctx, UserAuth_VerifyCaptcha_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthClient) SendSms(ctx context.Context, in *SendSmsReq, opts ...grpc.CallOption) (*SendSmsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSmsReply)
	err := c.cc.Invoke(ctx, UserAuth_SendSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthClient) VerifySms(ctx context.Context, in *VerifySmsReq, opts ...grpc.CallOption) (*VerifySmsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySmsReply)
	err := c.cc.Invoke(ctx, UserAuth_VerifySms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthClient) IssueToken(ctx context.Context, in *IssueTokenReq, opts ...grpc.CallOption) (*TokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenReply)
	err := c.cc.Invoke(ctx, UserAuth_IssueToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthClient) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*TokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenReply)
	err := c.cc.Invoke(ctx, UserAuth_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthClient) RevokeToken(ctx context.Context, in *RevokeTokenReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserAuth_RevokeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthClient) AddToBlacklist(ctx context.Context, in *AddToBlacklistReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserAuth_AddToBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthClient) CheckBlacklist(ctx context.Context, in *CheckBlacklistReq, opts ...grpc.CallOption) (*CheckBlacklistReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBlacklistReply)
	err := c.cc.Invoke(ctx, UserAuth_CheckBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAuthServer is the server API for UserAuth service.
// All implementations must embed UnimplementedUserAuthServer
// for forward compatibility.
//
// 用户认证服务 - 统一治理 Token/验证码/SMS/黑名单
type UserAuthServer interface {
	// ========== 验证码相关 ==========
	// 获取图形验证码
	GetCaptcha(context.Context, *emptypb.Empty) (*CaptchaReply, error)
	// 校验图形验证码（内部使用，不对外暴露 HTTP）
	VerifyCaptcha(context.Context, *VerifyCaptchaReq) (*VerifyCaptchaReply, error)
	// ========== 短信相关 ==========
	// 发送短信验证码
	SendSms(context.Context, *SendSmsReq) (*SendSmsReply, error)
	// 校验短信验证码（内部使用）
	VerifySms(context.Context, *VerifySmsReq) (*VerifySmsReply, error)
	// ========== Token 管理 ==========
	// 签发 Token（用于登录成功后）
	IssueToken(context.Context, *IssueTokenReq) (*TokenReply, error)
	// 刷新 Token
	RefreshToken(context.Context, *RefreshTokenReq) (*TokenReply, error)
	// 撤销 Token（登出）
	RevokeToken(context.Context, *RevokeTokenReq) (*emptypb.Empty, error)
	// ========== 黑名单管理 ==========
	// 添加到黑名单（内部使用）
	AddToBlacklist(context.Context, *AddToBlacklistReq) (*emptypb.Empty, error)
	// 检查是否在黑名单（内部使用）
	CheckBlacklist(context.Context, *CheckBlacklistReq) (*CheckBlacklistReply, error)
	mustEmbedUnimplementedUserAuthServer()
}

// UnimplementedUserAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserAuthServer struct{}

func (UnimplementedUserAuthServer) GetCaptcha(context.Context, *emptypb.Empty) (*CaptchaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCaptcha not implemented")
}
func (UnimplementedUserAuthServer) VerifyCaptcha(context.Context, *VerifyCaptchaReq) (*VerifyCaptchaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCaptcha not implemented")
}
func (UnimplementedUserAuthServer) SendSms(context.Context, *SendSmsReq) (*SendSmsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSms not implemented")
}
func (UnimplementedUserAuthServer) VerifySms(context.Context, *VerifySmsReq) (*VerifySmsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySms not implemented")
}
func (UnimplementedUserAuthServer) IssueToken(context.Context, *IssueTokenReq) (*TokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedUserAuthServer) RefreshToken(context.Context, *RefreshTokenReq) (*TokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedUserAuthServer) RevokeToken(context.Context, *RevokeTokenReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeToken not implemented")
}
func (UnimplementedUserAuthServer) AddToBlacklist(context.Context, *AddToBlacklistReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToBlacklist not implemented")
}
func (UnimplementedUserAuthServer) CheckBlacklist(context.Context, *CheckBlacklistReq) (*CheckBlacklistReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBlacklist not implemented")
}
func (UnimplementedUserAuthServer) mustEmbedUnimplementedUserAuthServer() {}
func (UnimplementedUserAuthServer) testEmbeddedByValue()                  {}

// UnsafeUserAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAuthServer will
// result in compilation errors.
type UnsafeUserAuthServer interface {
	mustEmbedUnimplementedUserAuthServer()
}

func RegisterUserAuthServer(s grpc.ServiceRegistrar, srv UserAuthServer) {
	// If the following call pancis, it indicates UnimplementedUserAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserAuth_ServiceDesc, srv)
}

func _UserAuth_GetCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServer).GetCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuth_GetCaptcha_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServer).GetCaptcha(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuth_VerifyCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCaptchaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServer).VerifyCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuth_VerifyCaptcha_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServer).VerifyCaptcha(ctx, req.(*VerifyCaptchaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuth_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuth_SendSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServer).SendSms(ctx, req.(*SendSmsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuth_VerifySms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySmsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServer).VerifySms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuth_VerifySms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServer).VerifySms(ctx, req.(*VerifySmsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuth_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuth_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServer).IssueToken(ctx, req.(*IssueTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuth_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuth_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServer).RefreshToken(ctx, req.(*RefreshTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuth_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuth_RevokeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServer).RevokeToken(ctx, req.(*RevokeTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuth_AddToBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServer).AddToBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuth_AddToBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServer).AddToBlacklist(ctx, req.(*AddToBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuth_CheckBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServer).CheckBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuth_CheckBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServer).CheckBlacklist(ctx, req.(*CheckBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAuth_ServiceDesc is the grpc.ServiceDesc for UserAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lushop.userauth.v1.UserAuth",
	HandlerType: (*UserAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCaptcha",
			Handler:    _UserAuth_GetCaptcha_Handler,
		},
		{
			MethodName: "VerifyCaptcha",
			Handler:    _UserAuth_VerifyCaptcha_Handler,
		},
		{
			MethodName: "SendSms",
			Handler:    _UserAuth_SendSms_Handler,
		},
		{
			MethodName: "VerifySms",
			Handler:    _UserAuth_VerifySms_Handler,
		},
		{
			MethodName: "IssueToken",
			Handler:    _UserAuth_IssueToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _UserAuth_RefreshToken_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _UserAuth_RevokeToken_Handler,
		},
		{
			MethodName: "AddToBlacklist",
			Handler:    _UserAuth_AddToBlacklist_Handler,
		},
		{
			MethodName: "CheckBlacklist",
			Handler:    _UserAuth_CheckBlacklist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userauth/v1/user_auth.proto",
}
