name: lushop.api
id: "1"
version: "1.0"
environment: "dev"

server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/lushop_user?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    password: "123456"
    read_timeout: 0.5s
    write_timeout: 0.5s
trace:
  endpoint: http://127.0.0.1:14268/api/traces
auth:
  jwt_key: "lCBOKwLE5w9JHriyihpaKKXiQGnqztgA/lmDYtfExC1BwYDdarpdW0hsVHGf0m9x"
service:
  user:
    endpoint: discovery:///lushop.user.service
  goods:
    endpoint: discovery:///lushop.goods.service
  user_auth:
    endpoint: "discovery:///lushop.userauth.service"  # 新增认证服务
  order:
    endpoint: "discovery:///lushop.order.service"  # 订单服务
  inventory:
    endpoint: "discovery:///lushop.inventory.service"  # 库存服务
  userop:
    endpoint: "discovery:///lushop.userop.service"  # 用户操作服务
sms:
  api_key: 'Ali_ApiKey'
  api_secret: 'Ali_ApiSecret'
  sign_name: '阿里云短信测试'
  template_code: 'SMS_154950909'
  phone_number: '19821216806'
  region_id: 'cn-hangzhou'
registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http