apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    server.name: kibana
    server.host: 0.0.0.0
    server.port: 5601
    elasticsearch.hosts:
      - http://elasticsearch.lushop.svc.cluster.local:9200
    elasticsearch.username: elastic
    elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
    xpack.security.enabled: true
    xpack.encryptedSavedObjects.encryptionKey: "a".repeat(32)
    xpack.reporting.encryptionKey: "a".repeat(32)
    xpack.security.encryptionKey: "a".repeat(32)
    logging.appenders:
      file:
        type: file
        fileName: /var/log/kibana/kibana.log
        layout:
          type: json
    logging.root:
      appenders:
        - default
        - file

