apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      nodePort: 30561
  type: NodePort
  selector:
    app.kubernetes.io/name: kibana

