apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: lushop
data:
  elasticsearch.yml: |
    cluster.name: lushop-es
    node.name: lushop-es-node
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
    network.host: 0.0.0.0
    http.port: 9200
    discovery.type: single-node
    bootstrap.memory_lock: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.graph.enabled: false
    xpack.watcher.enabled: false
    xpack.ml.enabled: false
