// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lushop/internal/authorization"
	"lushop/internal/biz"
	"lushop/internal/conf"
	"lushop/internal/data"
	"lushop/internal/server"
	"lushop/internal/service"
	"lushop/internal/task"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, confService *conf.Service, sms *conf.Sms, registry *conf.Registry, confTask *conf.Task, logger log.Logger) (*kratos.App, func(), error) {
	enforcer, err := authorization.NewEnforcer()
	if err != nil {
		return nil, nil, err
	}
	discovery := data.NewDiscovery(registry)
	userClient := data.NewUserServiceClient(auth, confService, discovery)
	userAuthClient := data.NewUserAuthClient(auth, confService, discovery)
	client := data.NewRedis(confData)
	dataData, err := data.NewData(confData, userClient, userAuthClient, logger, client)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserAuthRepoGRPC(dataData, logger)
	userAuthAdapter := biz.NewUserAuthAdapter(userAuthClient, logger)
	userUsecase := biz.NewUserUsecase(userRepo, userAuthAdapter, logger, auth, sms)
	lushopService := service.NewLushopService(userUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, auth, enforcer, lushopService, logger)
	grpcServer := server.NewGRPCServer(confServer, lushopService, logger)
	registrar := data.NewRegister(registry)
	asynqComponent, cleanup, err := task.NewAsynqComponent(confData, confTask, logger)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(logger, httpServer, grpcServer, registrar, asynqComponent)
	return app, func() {
		cleanup()
	}, nil
}
