apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-config
data:
  broker.conf: |
    brokerClusterName=DefaultCluster
    brokerName=broker-a
    brokerId=0
    deleteWhen=04
    fileReservedTime=48
    brokerRole=ASYNC_MASTER
    flushDiskType=ASYNC_FLUSH
    listenPort=10911
    autoCreateTopicEnable=true
    aclEnable=true
  rmq-proxy.json: |
    {
      "rocketMQClusterName": "DefaultCluster",
      "remotingListenPort": 18680,
      "grpcServerPort": 18681,
      "enableACL": true,
      "authenticationEnabled": true,
      "innerClientAuthenticationCredentials": "{\"accessKey\":\"lushop\", \"secretKey\":\"lushop123456\"}",
      "enableAclRpcHookForClusterMode": true,
      "authorizationEnabled": true
    }

