apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.yaml
  - namesrv-service.yaml
  - namesrv-deployment.yaml
  - broker-service.yaml
  - broker-statefulset.yaml
  - proxy-service.yaml
  - proxy-deployment.yaml
  - dashboard-service.yaml
  - dashboard-deployment.yaml

