apiVersion: v1
kind: Secret
metadata:
  name: rocketmq-credentials
type: Opaque
stringData:
  tools.yml: |
    accessKey: lushop
    secretKey: lushop123456
  users.properties: |
    admin=admin123
  dashboard-java-opts: >
    -Drocketmq.config.namesrvAddrs=rocketmq-namesrv:9876
    -Drocketmq.config.proxyAddrs=rocketmq-proxy:18680
    -Drocketmq.config.accessKey=lushop
    -Drocketmq.config.secretKey=lushop123456
    -Drocketmq.config.loginRequired=true

