apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-service
    spec:
      containers:
        - name: gateway
          image: lushop/gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
              name: http
            - containerPort: 9001
              name: grpc
          volumeMounts:
            - name: config
              mountPath: /data/conf
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: gateway-config

