apiVersion: v1
kind: Secret
metadata:
  name: lushop-secret
  namespace: lushop
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_PASSWORD: "123456"
  REDIS_PASSWORD: "123456"
  JWT_SECRET: "lushop-secret-key-2024"
