// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"userauth/internal/biz"
	"userauth/internal/conf"
	"userauth/internal/data"
	"userauth/internal/server"
	"userauth/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, sms *conf.Sms, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewRedis(confData, logger)
	dataData, cleanup, err := data.NewData(client, logger)
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(authRepo, auth, sms, logger)
	userAuthService := service.NewUserAuthService(authUsecase)
	grpcServer := server.NewGRPCServer(confServer, userAuthService, logger)
	registrar := server.NewRegistrar(registry, logger)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
