apiVersion: v1
kind: Service
metadata:
  name: userop-service
spec:
  ports:
    - name: http
      port: 8015
      targetPort: 8015
    - name: grpc
      port: 50055
      targetPort: 50055
  selector:
    app.kubernetes.io/name: userop-service

