// Code generated by MockGen. DO NOT EDIT.
// Source: order/internal/biz (interfaces: OrderRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	v1 "order/api/order/v1"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockOrderRepo is a mock of OrderRepo interface.
type MockOrderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepoMockRecorder
}

// MockOrderRepoMockRecorder is the mock recorder for MockOrderRepo.
type MockOrderRepoMockRecorder struct {
	mock *MockOrderRepo
}

// NewMockOrderRepo creates a new mock instance.
func NewMockOrderRepo(ctrl *gomock.Controller) *MockOrderRepo {
	mock := &MockOrderRepo{ctrl: ctrl}
	mock.recorder = &MockOrderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepo) EXPECT() *MockOrderRepoMockRecorder {
	return m.recorder
}

// CreateCartItem mocks base method.
func (m *MockOrderRepo) CreateCartItem(arg0 context.Context, arg1 *v1.CartItemRequest) (*v1.ShopCartInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCartItem", arg0, arg1)
	ret0, _ := ret[0].(*v1.ShopCartInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCartItem indicates an expected call of CreateCartItem.
func (mr *MockOrderRepoMockRecorder) CreateCartItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCartItem", reflect.TypeOf((*MockOrderRepo)(nil).CreateCartItem), arg0, arg1)
}

// CreateOrder mocks base method.
func (m *MockOrderRepo) CreateOrder(arg0 context.Context, arg1 *v1.OrderRequest) (*v1.OrderInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1)
	ret0, _ := ret[0].(*v1.OrderInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderRepoMockRecorder) CreateOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderRepo)(nil).CreateOrder), arg0, arg1)
}

// DeleteCartItem mocks base method.
func (m *MockOrderRepo) DeleteCartItem(arg0 context.Context, arg1 *v1.CartItemRequest) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItem", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCartItem indicates an expected call of DeleteCartItem.
func (mr *MockOrderRepoMockRecorder) DeleteCartItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItem", reflect.TypeOf((*MockOrderRepo)(nil).DeleteCartItem), arg0, arg1)
}

// GetCartList mocks base method.
func (m *MockOrderRepo) GetCartList(arg0 context.Context, arg1 int32) ([]*v1.ShopCartInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartList", arg0, arg1)
	ret0, _ := ret[0].([]*v1.ShopCartInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartList indicates an expected call of GetCartList.
func (mr *MockOrderRepoMockRecorder) GetCartList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartList", reflect.TypeOf((*MockOrderRepo)(nil).GetCartList), arg0, arg1)
}

// GetOrderDetail mocks base method.
func (m *MockOrderRepo) GetOrderDetail(arg0 context.Context, arg1 *v1.OrderRequest) (*v1.OrderInfoDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderDetail", arg0, arg1)
	ret0, _ := ret[0].(*v1.OrderInfoDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderDetail indicates an expected call of GetOrderDetail.
func (mr *MockOrderRepoMockRecorder) GetOrderDetail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderDetail", reflect.TypeOf((*MockOrderRepo)(nil).GetOrderDetail), arg0, arg1)
}

// GetOrderList mocks base method.
func (m *MockOrderRepo) GetOrderList(arg0 context.Context, arg1 *v1.OrderFilterRequest) ([]*v1.OrderInfoResponse, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderList", arg0, arg1)
	ret0, _ := ret[0].([]*v1.OrderInfoResponse)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrderList indicates an expected call of GetOrderList.
func (mr *MockOrderRepoMockRecorder) GetOrderList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderList", reflect.TypeOf((*MockOrderRepo)(nil).GetOrderList), arg0, arg1)
}

// HandleOrderTimeout mocks base method.
func (m *MockOrderRepo) HandleOrderTimeout(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleOrderTimeout", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleOrderTimeout indicates an expected call of HandleOrderTimeout.
func (mr *MockOrderRepoMockRecorder) HandleOrderTimeout(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleOrderTimeout", reflect.TypeOf((*MockOrderRepo)(nil).HandleOrderTimeout), arg0, arg1)
}

// UpdateCartItem mocks base method.
func (m *MockOrderRepo) UpdateCartItem(arg0 context.Context, arg1 *v1.CartItemRequest) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockOrderRepoMockRecorder) UpdateCartItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockOrderRepo)(nil).UpdateCartItem), arg0, arg1)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderRepo) UpdateOrderStatus(arg0 context.Context, arg1 *v1.OrderStatus) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderRepoMockRecorder) UpdateOrderStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderRepo)(nil).UpdateOrderStatus), arg0, arg1)
}
