// Code generated by MockGen. DO NOT EDIT.
// Source: inventory/internal/biz (interfaces: InventoryRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "inventory/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInventoryRepo is a mock of InventoryRepo interface.
type MockInventoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepoMockRecorder
}

// MockInventoryRepoMockRecorder is the mock recorder for MockInventoryRepo.
type MockInventoryRepoMockRecorder struct {
	mock *MockInventoryRepo
}

// NewMockInventoryRepo creates a new mock instance.
func NewMockInventoryRepo(ctrl *gomock.Controller) *MockInventoryRepo {
	mock := &MockInventoryRepo{ctrl: ctrl}
	mock.recorder = &MockInventoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepo) EXPECT() *MockInventoryRepoMockRecorder {
	return m.recorder
}

// AddInv mocks base method.
func (m *MockInventoryRepo) AddInv(arg0 context.Context, arg1 *domain.Inventory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInv", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddInv indicates an expected call of AddInv.
func (mr *MockInventoryRepoMockRecorder) AddInv(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInv", reflect.TypeOf((*MockInventoryRepo)(nil).AddInv), arg0, arg1)
}

// GetInvById mocks base method.
func (m *MockInventoryRepo) GetInvById(arg0 context.Context, arg1 int32) (*domain.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvById", arg0, arg1)
	ret0, _ := ret[0].(*domain.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvById indicates an expected call of GetInvById.
func (mr *MockInventoryRepoMockRecorder) GetInvById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvById", reflect.TypeOf((*MockInventoryRepo)(nil).GetInvById), arg0, arg1)
}

// Reback mocks base method.
func (m *MockInventoryRepo) Reback(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reback", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reback indicates an expected call of Reback.
func (mr *MockInventoryRepoMockRecorder) Reback(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reback", reflect.TypeOf((*MockInventoryRepo)(nil).Reback), arg0, arg1)
}

// Sell mocks base method.
func (m *MockInventoryRepo) Sell(arg0 context.Context, arg1 *domain.SellInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sell", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sell indicates an expected call of Sell.
func (mr *MockInventoryRepoMockRecorder) Sell(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sell", reflect.TypeOf((*MockInventoryRepo)(nil).Sell), arg0, arg1)
}
