apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
type: Opaque
stringData:
  mysql-root-password: "root123456"
  mysql-user: "lushop"
  mysql-password: "lushop123456"
  mysql-database: "lushop"

