// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"goods/internal/biz"
	"goods/internal/conf"
	"goods/internal/data"
	"goods/internal/server"
	"goods/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	elasticClient := data.NewElasticsearch(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, client, elasticClient)
	if err != nil {
		return nil, nil, err
	}
	brandRepo := data.NewBrandRepo(dataData, logger)
	brandUsecase := biz.NewBrandUsecase(brandRepo, logger)
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	categoryUsecase := biz.NewCategoryUsecase(categoryRepo, logger)
	goodsRepo := data.NewGoodsRepo(dataData, logger)
	transaction := data.NewTransaction(dataData)
	esGoodsRepo := data.NewEsGoodsRepo(dataData, logger)
	goodsUsecase := biz.NewGoodsUsecase(goodsRepo, brandRepo, categoryRepo, transaction, esGoodsRepo, logger)
	esGoodsUsecase := biz.NewEsGoodsUsecase(goodsRepo, esGoodsRepo, categoryRepo, logger)
	categoryBrandRepo := data.NewCategoryBrandRepo(dataData, logger)
	categoryBrandUsecase := biz.NewCategoryBrandUsecase(categoryBrandRepo, logger)
	bannerRepo := data.NewBannerRepo(dataData, logger)
	bannerUsecase := biz.NewBannerUsecase(bannerRepo, logger)
	goodsService := service.NewGoodsService(brandUsecase, categoryUsecase, goodsUsecase, esGoodsUsecase, categoryBrandUsecase, bannerUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, goodsService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
