// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: order/v1/order.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message Empty{}
// 用户信息id请求
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 购物车信息请求
type CartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Nums          int32                  `protobuf:"varint,4,opt,name=nums,proto3" json:"nums,omitempty"`
	Checked       bool                   `protobuf:"varint,5,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemRequest) Reset() {
	*x = CartItemRequest{}
	mi := &file_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemRequest) ProtoMessage() {}

func (x *CartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemRequest.ProtoReflect.Descriptor instead.
func (*CartItemRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *CartItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItemRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartItemRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CartItemRequest) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *CartItemRequest) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

// 订单信息请求
type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Post          string                 `protobuf:"bytes,6,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *OrderRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

// 订单信息查询分页请求
type OrderFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Pages         int32                  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	PagePerNums   int32                  `protobuf:"varint,3,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFilterRequest) Reset() {
	*x = OrderFilterRequest{}
	mi := &file_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFilterRequest) ProtoMessage() {}

func (x *OrderFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFilterRequest.ProtoReflect.Descriptor instead.
func (*OrderFilterRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderFilterRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderFilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *OrderFilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

// 订单状态 支付宝订单
type OrderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderStatus) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderStatus) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 购物车信息
type ShopCartInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Nums          int32                  `protobuf:"varint,4,opt,name=nums,proto3" json:"nums,omitempty"`
	Checked       bool                   `protobuf:"varint,5,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCartInfoResponse) Reset() {
	*x = ShopCartInfoResponse{}
	mi := &file_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCartInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartInfoResponse) ProtoMessage() {}

func (x *ShopCartInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartInfoResponse.ProtoReflect.Descriptor instead.
func (*ShopCartInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *ShopCartInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopCartInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShopCartInfoResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *ShopCartInfoResponse) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *ShopCartInfoResponse) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

// 购物车列表
type CartItemListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Total         int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*ShopCartInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemListResponse) Reset() {
	*x = CartItemListResponse{}
	mi := &file_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemListResponse) ProtoMessage() {}

func (x *CartItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemListResponse.ProtoReflect.Descriptor instead.
func (*CartItemListResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *CartItemListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CartItemListResponse) GetData() []*ShopCartInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 订单信息
type OrderInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	PayType       string                 `protobuf:"bytes,4,opt,name=payType,proto3" json:"payType,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Post          string                 `protobuf:"bytes,6,opt,name=post,proto3" json:"post,omitempty"`
	Total         float32                `protobuf:"fixed32,7,opt,name=total,proto3" json:"total,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,10,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AddTime       string                 `protobuf:"bytes,11,opt,name=addTime,proto3" json:"addTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoResponse) Reset() {
	*x = OrderInfoResponse{}
	mi := &file_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoResponse) ProtoMessage() {}

func (x *OrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrderInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfoResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderInfoResponse) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *OrderInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfoResponse) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *OrderInfoResponse) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderInfoResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *OrderInfoResponse) GetAddTime() string {
	if x != nil {
		return x.AddTime
	}
	return ""
}

// 订单列表信息
type OrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*OrderInfoResponse   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResponse) Reset() {
	*x = OrderListResponse{}
	mi := &file_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResponse) ProtoMessage() {}

func (x *OrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResponse.ProtoReflect.Descriptor instead.
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *OrderListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderListResponse) GetData() []*OrderInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 订单信息加入了商品的信息，对应model中的OrderGoods
type OrderItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsName     string                 `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	GoodsImage    string                 `protobuf:"bytes,5,opt,name=goodsImage,proto3" json:"goodsImage,omitempty"`
	GoodsPrice    float32                `protobuf:"fixed32,6,opt,name=goodsPrice,proto3" json:"goodsPrice,omitempty"`
	Nums          int32                  `protobuf:"varint,7,opt,name=nums,proto3" json:"nums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemResponse) Reset() {
	*x = OrderItemResponse{}
	mi := &file_order_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemResponse) ProtoMessage() {}

func (x *OrderItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemResponse.ProtoReflect.Descriptor instead.
func (*OrderItemResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *OrderItemResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItemResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItemResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderItemResponse) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *OrderItemResponse) GetGoodsImage() string {
	if x != nil {
		return x.GoodsImage
	}
	return ""
}

func (x *OrderItemResponse) GetGoodsPrice() float32 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *OrderItemResponse) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

// 订单的详情信息+订单中的商品信息
type OrderInfoDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfoResponse     `protobuf:"bytes,1,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	Goods         []*OrderItemResponse   `protobuf:"bytes,2,rep,name=goods,proto3" json:"goods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoDetailResponse) Reset() {
	*x = OrderInfoDetailResponse{}
	mi := &file_order_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoDetailResponse) ProtoMessage() {}

func (x *OrderInfoDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoDetailResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoDetailResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *OrderInfoDetailResponse) GetOrderInfo() *OrderInfoResponse {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

func (x *OrderInfoDetailResponse) GetGoods() []*OrderItemResponse {
	if x != nil {
		return x.Goods
	}
	return nil
}

var File_order_v1_order_proto protoreflect.FileDescriptor

const file_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/order.proto\x12\border.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x81\x01\n" +
	"\x0fCartItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x12\n" +
	"\x04nums\x18\x04 \x01(\x05R\x04nums\x12\x18\n" +
	"\achecked\x18\x05 \x01(\bR\achecked\"\x90\x01\n" +
	"\fOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04post\x18\x06 \x01(\tR\x04post\"d\n" +
	"\x12OrderFilterRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05pages\x18\x02 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x03 \x01(\x05R\vpagePerNums\"O\n" +
	"\vOrderStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x86\x01\n" +
	"\x14ShopCartInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x12\n" +
	"\x04nums\x18\x04 \x01(\x05R\x04nums\x12\x18\n" +
	"\achecked\x18\x05 \x01(\bR\achecked\"`\n" +
	"\x14CartItemListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x122\n" +
	"\x04data\x18\x02 \x03(\v2\x1e.order.v1.ShopCartInfoResponseR\x04data\"\x91\x02\n" +
	"\x11OrderInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\x12\x18\n" +
	"\apayType\x18\x04 \x01(\tR\apayType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04post\x18\x06 \x01(\tR\x04post\x12\x14\n" +
	"\x05total\x18\a \x01(\x02R\x05total\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\n" +
	" \x01(\tR\x06mobile\x12\x18\n" +
	"\aaddTime\x18\v \x01(\tR\aaddTime\"Z\n" +
	"\x11OrderListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12/\n" +
	"\x04data\x18\x02 \x03(\v2\x1b.order.v1.OrderInfoResponseR\x04data\"\xc9\x01\n" +
	"\x11OrderItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aorderId\x18\x02 \x01(\x05R\aorderId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x1c\n" +
	"\tgoodsName\x18\x04 \x01(\tR\tgoodsName\x12\x1e\n" +
	"\n" +
	"goodsImage\x18\x05 \x01(\tR\n" +
	"goodsImage\x12\x1e\n" +
	"\n" +
	"goodsPrice\x18\x06 \x01(\x02R\n" +
	"goodsPrice\x12\x12\n" +
	"\x04nums\x18\a \x01(\x05R\x04nums\"\x87\x01\n" +
	"\x17OrderInfoDetailResponse\x129\n" +
	"\torderInfo\x18\x01 \x01(\v2\x1b.order.v1.OrderInfoResponseR\torderInfo\x121\n" +
	"\x05goods\x18\x02 \x03(\v2\x1b.order.v1.OrderItemResponseR\x05goods2\xbc\x04\n" +
	"\x05Order\x12B\n" +
	"\fCartItemList\x12\x12.order.v1.UserInfo\x1a\x1e.order.v1.CartItemListResponse\x12K\n" +
	"\x0eCreateCartItem\x12\x19.order.v1.CartItemRequest\x1a\x1e.order.v1.ShopCartInfoResponse\x12C\n" +
	"\x0eUpdateCartItem\x12\x19.order.v1.CartItemRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x0eDeleteCartItem\x12\x19.order.v1.CartItemRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\vCreateOrder\x12\x16.order.v1.OrderRequest\x1a\x1b.order.v1.OrderInfoResponse\x12F\n" +
	"\tOrderList\x12\x1c.order.v1.OrderFilterRequest\x1a\x1b.order.v1.OrderListResponse\x12H\n" +
	"\vOrderDetail\x12\x16.order.v1.OrderRequest\x1a!.order.v1.OrderInfoDetailResponse\x12B\n" +
	"\x11UpdateOrderStatus\x12\x15.order.v1.OrderStatus\x1a\x16.google.protobuf.EmptyB\x17Z\x15order/api/order/v1;v1b\x06proto3"

var (
	file_order_v1_order_proto_rawDescOnce sync.Once
	file_order_v1_order_proto_rawDescData []byte
)

func file_order_v1_order_proto_rawDescGZIP() []byte {
	file_order_v1_order_proto_rawDescOnce.Do(func() {
		file_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)))
	})
	return file_order_v1_order_proto_rawDescData
}

var file_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_order_v1_order_proto_goTypes = []any{
	(*UserInfo)(nil),                // 0: order.v1.UserInfo
	(*CartItemRequest)(nil),         // 1: order.v1.CartItemRequest
	(*OrderRequest)(nil),            // 2: order.v1.OrderRequest
	(*OrderFilterRequest)(nil),      // 3: order.v1.OrderFilterRequest
	(*OrderStatus)(nil),             // 4: order.v1.OrderStatus
	(*ShopCartInfoResponse)(nil),    // 5: order.v1.ShopCartInfoResponse
	(*CartItemListResponse)(nil),    // 6: order.v1.CartItemListResponse
	(*OrderInfoResponse)(nil),       // 7: order.v1.OrderInfoResponse
	(*OrderListResponse)(nil),       // 8: order.v1.OrderListResponse
	(*OrderItemResponse)(nil),       // 9: order.v1.OrderItemResponse
	(*OrderInfoDetailResponse)(nil), // 10: order.v1.OrderInfoDetailResponse
	(*emptypb.Empty)(nil),           // 11: google.protobuf.Empty
}
var file_order_v1_order_proto_depIdxs = []int32{
	5,  // 0: order.v1.CartItemListResponse.data:type_name -> order.v1.ShopCartInfoResponse
	7,  // 1: order.v1.OrderListResponse.data:type_name -> order.v1.OrderInfoResponse
	7,  // 2: order.v1.OrderInfoDetailResponse.orderInfo:type_name -> order.v1.OrderInfoResponse
	9,  // 3: order.v1.OrderInfoDetailResponse.goods:type_name -> order.v1.OrderItemResponse
	0,  // 4: order.v1.Order.CartItemList:input_type -> order.v1.UserInfo
	1,  // 5: order.v1.Order.CreateCartItem:input_type -> order.v1.CartItemRequest
	1,  // 6: order.v1.Order.UpdateCartItem:input_type -> order.v1.CartItemRequest
	1,  // 7: order.v1.Order.DeleteCartItem:input_type -> order.v1.CartItemRequest
	2,  // 8: order.v1.Order.CreateOrder:input_type -> order.v1.OrderRequest
	3,  // 9: order.v1.Order.OrderList:input_type -> order.v1.OrderFilterRequest
	2,  // 10: order.v1.Order.OrderDetail:input_type -> order.v1.OrderRequest
	4,  // 11: order.v1.Order.UpdateOrderStatus:input_type -> order.v1.OrderStatus
	6,  // 12: order.v1.Order.CartItemList:output_type -> order.v1.CartItemListResponse
	5,  // 13: order.v1.Order.CreateCartItem:output_type -> order.v1.ShopCartInfoResponse
	11, // 14: order.v1.Order.UpdateCartItem:output_type -> google.protobuf.Empty
	11, // 15: order.v1.Order.DeleteCartItem:output_type -> google.protobuf.Empty
	7,  // 16: order.v1.Order.CreateOrder:output_type -> order.v1.OrderInfoResponse
	8,  // 17: order.v1.Order.OrderList:output_type -> order.v1.OrderListResponse
	10, // 18: order.v1.Order.OrderDetail:output_type -> order.v1.OrderInfoDetailResponse
	11, // 19: order.v1.Order.UpdateOrderStatus:output_type -> google.protobuf.Empty
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_order_v1_order_proto_init() }
func file_order_v1_order_proto_init() {
	if File_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_proto_goTypes,
		DependencyIndexes: file_order_v1_order_proto_depIdxs,
		MessageInfos:      file_order_v1_order_proto_msgTypes,
	}.Build()
	File_order_v1_order_proto = out.File
	file_order_v1_order_proto_goTypes = nil
	file_order_v1_order_proto_depIdxs = nil
}
