// Code generated by MockGen. DO NOT EDIT.
// Source: goods/internal/biz (interfaces: BrandRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	biz "goods/internal/biz"
	domain "goods/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBrandRepo is a mock of BrandRepo interface.
type MockBrandRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBrandRepoMockRecorder
}

// MockBrandRepoMockRecorder is the mock recorder for MockBrandRepo.
type MockBrandRepoMockRecorder struct {
	mock *MockBrandRepo
}

// NewMockBrandRepo creates a new mock instance.
func NewMockBrandRepo(ctrl *gomock.Controller) *MockBrandRepo {
	mock := &MockBrandRepo{ctrl: ctrl}
	mock.recorder = &MockBrandRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrandRepo) EXPECT() *MockBrandRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBrandRepo) Create(arg0 context.Context, arg1 *domain.Brand) (*domain.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*domain.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBrandRepoMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBrandRepo)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockBrandRepo) Delete(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBrandRepoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBrandRepo)(nil).Delete), arg0, arg1)
}

// GetBrandByID mocks base method.
func (m *MockBrandRepo) GetBrandByID(arg0 context.Context, arg1 int32) (*domain.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrandByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrandByID indicates an expected call of GetBrandByID.
func (mr *MockBrandRepoMockRecorder) GetBrandByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrandByID", reflect.TypeOf((*MockBrandRepo)(nil).GetBrandByID), arg0, arg1)
}

// GetBrandByName mocks base method.
func (m *MockBrandRepo) GetBrandByName(arg0 context.Context, arg1 string) (*domain.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrandByName", arg0, arg1)
	ret0, _ := ret[0].(*domain.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrandByName indicates an expected call of GetBrandByName.
func (mr *MockBrandRepoMockRecorder) GetBrandByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrandByName", reflect.TypeOf((*MockBrandRepo)(nil).GetBrandByName), arg0, arg1)
}

// IsBrand mocks base method.
func (m *MockBrandRepo) IsBrand(arg0 context.Context, arg1 []int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBrand", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsBrand indicates an expected call of IsBrand.
func (mr *MockBrandRepoMockRecorder) IsBrand(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBrand", reflect.TypeOf((*MockBrandRepo)(nil).IsBrand), arg0, arg1)
}

// List mocks base method.
func (m *MockBrandRepo) List(arg0 context.Context, arg1 *biz.Pagination) ([]*domain.Brand, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Brand)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockBrandRepoMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBrandRepo)(nil).List), arg0, arg1)
}

// ListByIds mocks base method.
func (m *MockBrandRepo) ListByIds(arg0 context.Context, arg1 ...int32) (domain.BrandList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListByIds", varargs...)
	ret0, _ := ret[0].(domain.BrandList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIds indicates an expected call of ListByIds.
func (mr *MockBrandRepoMockRecorder) ListByIds(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIds", reflect.TypeOf((*MockBrandRepo)(nil).ListByIds), varargs...)
}

// Update mocks base method.
func (m *MockBrandRepo) Update(arg0 context.Context, arg1 *domain.Brand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBrandRepoMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBrandRepo)(nil).Update), arg0, arg1)
}
