// Code generated by MockGen. DO NOT EDIT.
// Source: goods/internal/biz (interfaces: CategoryRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "goods/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCategoryRepo is a mock of CategoryRepo interface.
type MockCategoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepoMockRecorder
}

// MockCategoryRepoMockRecorder is the mock recorder for MockCategoryRepo.
type MockCategoryRepoMockRecorder struct {
	mock *MockCategoryRepo
}

// NewMockCategoryRepo creates a new mock instance.
func NewMockCategoryRepo(ctrl *gomock.Controller) *MockCategoryRepo {
	mock := &MockCategoryRepo{ctrl: ctrl}
	mock.recorder = &MockCategoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepo) EXPECT() *MockCategoryRepoMockRecorder {
	return m.recorder
}

// AddCategory mocks base method.
func (m *MockCategoryRepo) AddCategory(arg0 context.Context, arg1 *domain.CategoryInfo) (*domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCategory", arg0, arg1)
	ret0, _ := ret[0].(*domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCategory indicates an expected call of AddCategory.
func (mr *MockCategoryRepoMockRecorder) AddCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCategory", reflect.TypeOf((*MockCategoryRepo)(nil).AddCategory), arg0, arg1)
}

// CategoryList mocks base method.
func (m *MockCategoryRepo) CategoryList(arg0 context.Context) ([]*domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategoryList", arg0)
	ret0, _ := ret[0].([]*domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CategoryList indicates an expected call of CategoryList.
func (mr *MockCategoryRepoMockRecorder) CategoryList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategoryList", reflect.TypeOf((*MockCategoryRepo)(nil).CategoryList), arg0)
}

// DeleteCategory mocks base method.
func (m *MockCategoryRepo) DeleteCategory(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockCategoryRepoMockRecorder) DeleteCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockCategoryRepo)(nil).DeleteCategory), arg0, arg1)
}

// GetCategoryAll mocks base method.
func (m *MockCategoryRepo) GetCategoryAll(arg0 context.Context, arg1, arg2 int32) ([]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryAll indicates an expected call of GetCategoryAll.
func (mr *MockCategoryRepoMockRecorder) GetCategoryAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryAll", reflect.TypeOf((*MockCategoryRepo)(nil).GetCategoryAll), arg0, arg1, arg2)
}

// GetCategoryByID mocks base method.
func (m *MockCategoryRepo) GetCategoryByID(arg0 context.Context, arg1 int32) (*domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByID indicates an expected call of GetCategoryByID.
func (mr *MockCategoryRepoMockRecorder) GetCategoryByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByID", reflect.TypeOf((*MockCategoryRepo)(nil).GetCategoryByID), arg0, arg1)
}

// SubCategory mocks base method.
func (m *MockCategoryRepo) SubCategory(arg0 context.Context, arg1 *domain.Category) ([]*domain.CategoryList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubCategory", arg0, arg1)
	ret0, _ := ret[0].([]*domain.CategoryList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubCategory indicates an expected call of SubCategory.
func (mr *MockCategoryRepoMockRecorder) SubCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubCategory", reflect.TypeOf((*MockCategoryRepo)(nil).SubCategory), arg0, arg1)
}

// UpdateCategory mocks base method.
func (m *MockCategoryRepo) UpdateCategory(arg0 context.Context, arg1 *domain.CategoryInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockCategoryRepoMockRecorder) UpdateCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockCategoryRepo)(nil).UpdateCategory), arg0, arg1)
}
