// Code generated by MockGen. DO NOT EDIT.
// Source: goods/internal/biz (interfaces: GoodsRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "goods/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGoodsRepo is a mock of GoodsRepo interface.
type MockGoodsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGoodsRepoMockRecorder
}

// MockGoodsRepoMockRecorder is the mock recorder for MockGoodsRepo.
type MockGoodsRepoMockRecorder struct {
	mock *MockGoodsRepo
}

// NewMockGoodsRepo creates a new mock instance.
func NewMockGoodsRepo(ctrl *gomock.Controller) *MockGoodsRepo {
	mock := &MockGoodsRepo{ctrl: ctrl}
	mock.recorder = &MockGoodsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoodsRepo) EXPECT() *MockGoodsRepoMockRecorder {
	return m.recorder
}

// CreateGoods mocks base method.
func (m *MockGoodsRepo) CreateGoods(arg0 context.Context, arg1 *domain.Goods) (*domain.Goods, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGoods", arg0, arg1)
	ret0, _ := ret[0].(*domain.Goods)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGoods indicates an expected call of CreateGoods.
func (mr *MockGoodsRepoMockRecorder) CreateGoods(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGoods", reflect.TypeOf((*MockGoodsRepo)(nil).CreateGoods), arg0, arg1)
}

// DeleteGoods mocks base method.
func (m *MockGoodsRepo) DeleteGoods(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGoods", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGoods indicates an expected call of DeleteGoods.
func (mr *MockGoodsRepoMockRecorder) DeleteGoods(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGoods", reflect.TypeOf((*MockGoodsRepo)(nil).DeleteGoods), arg0, arg1)
}

// GoodsByID mocks base method.
func (m *MockGoodsRepo) GoodsByID(arg0 context.Context, arg1 int64) (*domain.Goods, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoodsByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Goods)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoodsByID indicates an expected call of GoodsByID.
func (mr *MockGoodsRepoMockRecorder) GoodsByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoodsByID", reflect.TypeOf((*MockGoodsRepo)(nil).GoodsByID), arg0, arg1)
}

// GoodsListByIDs mocks base method.
func (m *MockGoodsRepo) GoodsListByIDs(arg0 context.Context, arg1 ...int64) ([]*domain.Goods, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GoodsListByIDs", varargs...)
	ret0, _ := ret[0].([]*domain.Goods)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoodsListByIDs indicates an expected call of GoodsListByIDs.
func (mr *MockGoodsRepoMockRecorder) GoodsListByIDs(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoodsListByIDs", reflect.TypeOf((*MockGoodsRepo)(nil).GoodsListByIDs), varargs...)
}

// UpdateGoods mocks base method.
func (m *MockGoodsRepo) UpdateGoods(arg0 context.Context, arg1 *domain.Goods) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGoods", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGoods indicates an expected call of UpdateGoods.
func (mr *MockGoodsRepoMockRecorder) UpdateGoods(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGoods", reflect.TypeOf((*MockGoodsRepo)(nil).UpdateGoods), arg0, arg1)
}
