// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: userop/v1/userop.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddressRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddressRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddressRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddressRequestMultiError,
// or nil if none found.
func (m *AddressRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddressRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Province

	// no validation rules for City

	// no validation rules for District

	// no validation rules for Address

	// no validation rules for SignerName

	// no validation rules for SignerMobile

	if len(errors) > 0 {
		return AddressRequestMultiError(errors)
	}

	return nil
}

// AddressRequestMultiError is an error wrapping multiple validation errors
// returned by AddressRequest.ValidateAll() if the designated constraints
// aren't met.
type AddressRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddressRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddressRequestMultiError) AllErrors() []error { return m }

// AddressRequestValidationError is the validation error returned by
// AddressRequest.Validate if the designated constraints aren't met.
type AddressRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddressRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddressRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddressRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddressRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddressRequestValidationError) ErrorName() string { return "AddressRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddressRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddressRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddressRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddressRequestValidationError{}

// Validate checks the field values on AddressResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddressResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddressResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddressResponseMultiError, or nil if none found.
func (m *AddressResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddressResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Province

	// no validation rules for City

	// no validation rules for District

	// no validation rules for Address

	// no validation rules for SignerName

	// no validation rules for SignerMobile

	if len(errors) > 0 {
		return AddressResponseMultiError(errors)
	}

	return nil
}

// AddressResponseMultiError is an error wrapping multiple validation errors
// returned by AddressResponse.ValidateAll() if the designated constraints
// aren't met.
type AddressResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddressResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddressResponseMultiError) AllErrors() []error { return m }

// AddressResponseValidationError is the validation error returned by
// AddressResponse.Validate if the designated constraints aren't met.
type AddressResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddressResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddressResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddressResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddressResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddressResponseValidationError) ErrorName() string { return "AddressResponseValidationError" }

// Error satisfies the builtin error interface
func (e AddressResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddressResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddressResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddressResponseValidationError{}

// Validate checks the field values on AddressListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddressListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddressListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddressListResponseMultiError, or nil if none found.
func (m *AddressListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddressListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AddressListResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AddressListResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AddressListResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AddressListResponseMultiError(errors)
	}

	return nil
}

// AddressListResponseMultiError is an error wrapping multiple validation
// errors returned by AddressListResponse.ValidateAll() if the designated
// constraints aren't met.
type AddressListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddressListResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddressListResponseMultiError) AllErrors() []error { return m }

// AddressListResponseValidationError is the validation error returned by
// AddressListResponse.Validate if the designated constraints aren't met.
type AddressListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddressListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddressListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddressListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddressListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddressListResponseValidationError) ErrorName() string {
	return "AddressListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddressListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddressListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddressListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddressListResponseValidationError{}

// Validate checks the field values on MessageRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessageRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MessageRequestMultiError,
// or nil if none found.
func (m *MessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for MessageType

	// no validation rules for Subject

	// no validation rules for Message

	// no validation rules for File

	if len(errors) > 0 {
		return MessageRequestMultiError(errors)
	}

	return nil
}

// MessageRequestMultiError is an error wrapping multiple validation errors
// returned by MessageRequest.ValidateAll() if the designated constraints
// aren't met.
type MessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageRequestMultiError) AllErrors() []error { return m }

// MessageRequestValidationError is the validation error returned by
// MessageRequest.Validate if the designated constraints aren't met.
type MessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageRequestValidationError) ErrorName() string { return "MessageRequestValidationError" }

// Error satisfies the builtin error interface
func (e MessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageRequestValidationError{}

// Validate checks the field values on MessageResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MessageResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MessageResponseMultiError, or nil if none found.
func (m *MessageResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MessageResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for MessageType

	// no validation rules for Subject

	// no validation rules for Message

	// no validation rules for File

	if len(errors) > 0 {
		return MessageResponseMultiError(errors)
	}

	return nil
}

// MessageResponseMultiError is an error wrapping multiple validation errors
// returned by MessageResponse.ValidateAll() if the designated constraints
// aren't met.
type MessageResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageResponseMultiError) AllErrors() []error { return m }

// MessageResponseValidationError is the validation error returned by
// MessageResponse.Validate if the designated constraints aren't met.
type MessageResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageResponseValidationError) ErrorName() string { return "MessageResponseValidationError" }

// Error satisfies the builtin error interface
func (e MessageResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageResponseValidationError{}

// Validate checks the field values on MessageListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MessageListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessageListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MessageListResponseMultiError, or nil if none found.
func (m *MessageListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MessageListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MessageListResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MessageListResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MessageListResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MessageListResponseMultiError(errors)
	}

	return nil
}

// MessageListResponseMultiError is an error wrapping multiple validation
// errors returned by MessageListResponse.ValidateAll() if the designated
// constraints aren't met.
type MessageListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageListResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageListResponseMultiError) AllErrors() []error { return m }

// MessageListResponseValidationError is the validation error returned by
// MessageListResponse.Validate if the designated constraints aren't met.
type MessageListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageListResponseValidationError) ErrorName() string {
	return "MessageListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MessageListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageListResponseValidationError{}

// Validate checks the field values on UserFavRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserFavRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserFavRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserFavRequestMultiError,
// or nil if none found.
func (m *UserFavRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserFavRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for GoodsId

	if len(errors) > 0 {
		return UserFavRequestMultiError(errors)
	}

	return nil
}

// UserFavRequestMultiError is an error wrapping multiple validation errors
// returned by UserFavRequest.ValidateAll() if the designated constraints
// aren't met.
type UserFavRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserFavRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserFavRequestMultiError) AllErrors() []error { return m }

// UserFavRequestValidationError is the validation error returned by
// UserFavRequest.Validate if the designated constraints aren't met.
type UserFavRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserFavRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserFavRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserFavRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserFavRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserFavRequestValidationError) ErrorName() string { return "UserFavRequestValidationError" }

// Error satisfies the builtin error interface
func (e UserFavRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserFavRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserFavRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserFavRequestValidationError{}

// Validate checks the field values on UserFavResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserFavResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserFavResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserFavResponseMultiError, or nil if none found.
func (m *UserFavResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UserFavResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for GoodsId

	if len(errors) > 0 {
		return UserFavResponseMultiError(errors)
	}

	return nil
}

// UserFavResponseMultiError is an error wrapping multiple validation errors
// returned by UserFavResponse.ValidateAll() if the designated constraints
// aren't met.
type UserFavResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserFavResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserFavResponseMultiError) AllErrors() []error { return m }

// UserFavResponseValidationError is the validation error returned by
// UserFavResponse.Validate if the designated constraints aren't met.
type UserFavResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserFavResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserFavResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserFavResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserFavResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserFavResponseValidationError) ErrorName() string { return "UserFavResponseValidationError" }

// Error satisfies the builtin error interface
func (e UserFavResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserFavResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserFavResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserFavResponseValidationError{}

// Validate checks the field values on UserFavListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserFavListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserFavListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserFavListResponseMultiError, or nil if none found.
func (m *UserFavListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UserFavListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserFavListResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserFavListResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserFavListResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UserFavListResponseMultiError(errors)
	}

	return nil
}

// UserFavListResponseMultiError is an error wrapping multiple validation
// errors returned by UserFavListResponse.ValidateAll() if the designated
// constraints aren't met.
type UserFavListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserFavListResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserFavListResponseMultiError) AllErrors() []error { return m }

// UserFavListResponseValidationError is the validation error returned by
// UserFavListResponse.Validate if the designated constraints aren't met.
type UserFavListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserFavListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserFavListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserFavListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserFavListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserFavListResponseValidationError) ErrorName() string {
	return "UserFavListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UserFavListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserFavListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserFavListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserFavListResponseValidationError{}
