// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: service/userauth/v1/user_auth.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CaptchaReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CaptchaReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CaptchaReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CaptchaReplyMultiError, or
// nil if none found.
func (m *CaptchaReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CaptchaReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CaptchaId

	// no validation rules for PicPath

	if len(errors) > 0 {
		return CaptchaReplyMultiError(errors)
	}

	return nil
}

// CaptchaReplyMultiError is an error wrapping multiple validation errors
// returned by CaptchaReply.ValidateAll() if the designated constraints aren't met.
type CaptchaReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CaptchaReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CaptchaReplyMultiError) AllErrors() []error { return m }

// CaptchaReplyValidationError is the validation error returned by
// CaptchaReply.Validate if the designated constraints aren't met.
type CaptchaReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CaptchaReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CaptchaReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CaptchaReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CaptchaReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CaptchaReplyValidationError) ErrorName() string { return "CaptchaReplyValidationError" }

// Error satisfies the builtin error interface
func (e CaptchaReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCaptchaReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CaptchaReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CaptchaReplyValidationError{}

// Validate checks the field values on VerifyCaptchaReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *VerifyCaptchaReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VerifyCaptchaReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VerifyCaptchaReqMultiError, or nil if none found.
func (m *VerifyCaptchaReq) ValidateAll() error {
	return m.validate(true)
}

func (m *VerifyCaptchaReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCaptchaId()) < 1 {
		err := VerifyCaptchaReqValidationError{
			field:  "CaptchaId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCaptcha()) < 1 {
		err := VerifyCaptchaReqValidationError{
			field:  "Captcha",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return VerifyCaptchaReqMultiError(errors)
	}

	return nil
}

// VerifyCaptchaReqMultiError is an error wrapping multiple validation errors
// returned by VerifyCaptchaReq.ValidateAll() if the designated constraints
// aren't met.
type VerifyCaptchaReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VerifyCaptchaReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VerifyCaptchaReqMultiError) AllErrors() []error { return m }

// VerifyCaptchaReqValidationError is the validation error returned by
// VerifyCaptchaReq.Validate if the designated constraints aren't met.
type VerifyCaptchaReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyCaptchaReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyCaptchaReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyCaptchaReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyCaptchaReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyCaptchaReqValidationError) ErrorName() string { return "VerifyCaptchaReqValidationError" }

// Error satisfies the builtin error interface
func (e VerifyCaptchaReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyCaptchaReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyCaptchaReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyCaptchaReqValidationError{}

// Validate checks the field values on VerifyCaptchaReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VerifyCaptchaReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VerifyCaptchaReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VerifyCaptchaReplyMultiError, or nil if none found.
func (m *VerifyCaptchaReply) ValidateAll() error {
	return m.validate(true)
}

func (m *VerifyCaptchaReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return VerifyCaptchaReplyMultiError(errors)
	}

	return nil
}

// VerifyCaptchaReplyMultiError is an error wrapping multiple validation errors
// returned by VerifyCaptchaReply.ValidateAll() if the designated constraints
// aren't met.
type VerifyCaptchaReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VerifyCaptchaReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VerifyCaptchaReplyMultiError) AllErrors() []error { return m }

// VerifyCaptchaReplyValidationError is the validation error returned by
// VerifyCaptchaReply.Validate if the designated constraints aren't met.
type VerifyCaptchaReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyCaptchaReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyCaptchaReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyCaptchaReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyCaptchaReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyCaptchaReplyValidationError) ErrorName() string {
	return "VerifyCaptchaReplyValidationError"
}

// Error satisfies the builtin error interface
func (e VerifyCaptchaReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyCaptchaReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyCaptchaReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyCaptchaReplyValidationError{}

// Validate checks the field values on SendSmsReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendSmsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendSmsReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendSmsReqMultiError, or
// nil if none found.
func (m *SendSmsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SendSmsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetMobile()) != 11 {
		err := SendSmsReqValidationError{
			field:  "Mobile",
			reason: "value length must be 11 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if len(errors) > 0 {
		return SendSmsReqMultiError(errors)
	}

	return nil
}

// SendSmsReqMultiError is an error wrapping multiple validation errors
// returned by SendSmsReq.ValidateAll() if the designated constraints aren't met.
type SendSmsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendSmsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendSmsReqMultiError) AllErrors() []error { return m }

// SendSmsReqValidationError is the validation error returned by
// SendSmsReq.Validate if the designated constraints aren't met.
type SendSmsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendSmsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendSmsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendSmsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendSmsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendSmsReqValidationError) ErrorName() string { return "SendSmsReqValidationError" }

// Error satisfies the builtin error interface
func (e SendSmsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendSmsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendSmsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendSmsReqValidationError{}

// Validate checks the field values on SendSmsReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendSmsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendSmsReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendSmsReplyMultiError, or
// nil if none found.
func (m *SendSmsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SendSmsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return SendSmsReplyMultiError(errors)
	}

	return nil
}

// SendSmsReplyMultiError is an error wrapping multiple validation errors
// returned by SendSmsReply.ValidateAll() if the designated constraints aren't met.
type SendSmsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendSmsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendSmsReplyMultiError) AllErrors() []error { return m }

// SendSmsReplyValidationError is the validation error returned by
// SendSmsReply.Validate if the designated constraints aren't met.
type SendSmsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendSmsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendSmsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendSmsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendSmsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendSmsReplyValidationError) ErrorName() string { return "SendSmsReplyValidationError" }

// Error satisfies the builtin error interface
func (e SendSmsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendSmsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendSmsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendSmsReplyValidationError{}

// Validate checks the field values on VerifySmsReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VerifySmsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VerifySmsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VerifySmsReqMultiError, or
// nil if none found.
func (m *VerifySmsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *VerifySmsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetMobile()) != 11 {
		err := VerifySmsReqValidationError{
			field:  "Mobile",
			reason: "value length must be 11 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if utf8.RuneCountInString(m.GetSmsCode()) != 6 {
		err := VerifySmsReqValidationError{
			field:  "SmsCode",
			reason: "value length must be 6 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if len(errors) > 0 {
		return VerifySmsReqMultiError(errors)
	}

	return nil
}

// VerifySmsReqMultiError is an error wrapping multiple validation errors
// returned by VerifySmsReq.ValidateAll() if the designated constraints aren't met.
type VerifySmsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VerifySmsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VerifySmsReqMultiError) AllErrors() []error { return m }

// VerifySmsReqValidationError is the validation error returned by
// VerifySmsReq.Validate if the designated constraints aren't met.
type VerifySmsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifySmsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifySmsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifySmsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifySmsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifySmsReqValidationError) ErrorName() string { return "VerifySmsReqValidationError" }

// Error satisfies the builtin error interface
func (e VerifySmsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifySmsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifySmsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifySmsReqValidationError{}

// Validate checks the field values on VerifySmsReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VerifySmsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VerifySmsReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VerifySmsReplyMultiError,
// or nil if none found.
func (m *VerifySmsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *VerifySmsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return VerifySmsReplyMultiError(errors)
	}

	return nil
}

// VerifySmsReplyMultiError is an error wrapping multiple validation errors
// returned by VerifySmsReply.ValidateAll() if the designated constraints
// aren't met.
type VerifySmsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VerifySmsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VerifySmsReplyMultiError) AllErrors() []error { return m }

// VerifySmsReplyValidationError is the validation error returned by
// VerifySmsReply.Validate if the designated constraints aren't met.
type VerifySmsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifySmsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifySmsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifySmsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifySmsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifySmsReplyValidationError) ErrorName() string { return "VerifySmsReplyValidationError" }

// Error satisfies the builtin error interface
func (e VerifySmsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifySmsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifySmsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifySmsReplyValidationError{}

// Validate checks the field values on IssueTokenReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IssueTokenReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IssueTokenReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IssueTokenReqMultiError, or
// nil if none found.
func (m *IssueTokenReq) ValidateAll() error {
	return m.validate(true)
}

func (m *IssueTokenReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := IssueTokenReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for NickName

	// no validation rules for Role

	if len(errors) > 0 {
		return IssueTokenReqMultiError(errors)
	}

	return nil
}

// IssueTokenReqMultiError is an error wrapping multiple validation errors
// returned by IssueTokenReq.ValidateAll() if the designated constraints
// aren't met.
type IssueTokenReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IssueTokenReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IssueTokenReqMultiError) AllErrors() []error { return m }

// IssueTokenReqValidationError is the validation error returned by
// IssueTokenReq.Validate if the designated constraints aren't met.
type IssueTokenReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IssueTokenReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IssueTokenReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IssueTokenReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IssueTokenReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IssueTokenReqValidationError) ErrorName() string { return "IssueTokenReqValidationError" }

// Error satisfies the builtin error interface
func (e IssueTokenReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIssueTokenReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IssueTokenReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IssueTokenReqValidationError{}

// Validate checks the field values on TokenReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TokenReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TokenReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TokenReplyMultiError, or
// nil if none found.
func (m *TokenReply) ValidateAll() error {
	return m.validate(true)
}

func (m *TokenReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessToken

	// no validation rules for RefreshToken

	// no validation rules for ExpiredAt

	if len(errors) > 0 {
		return TokenReplyMultiError(errors)
	}

	return nil
}

// TokenReplyMultiError is an error wrapping multiple validation errors
// returned by TokenReply.ValidateAll() if the designated constraints aren't met.
type TokenReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TokenReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TokenReplyMultiError) AllErrors() []error { return m }

// TokenReplyValidationError is the validation error returned by
// TokenReply.Validate if the designated constraints aren't met.
type TokenReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TokenReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TokenReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TokenReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TokenReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TokenReplyValidationError) ErrorName() string { return "TokenReplyValidationError" }

// Error satisfies the builtin error interface
func (e TokenReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTokenReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TokenReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TokenReplyValidationError{}

// Validate checks the field values on RefreshTokenReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RefreshTokenReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RefreshTokenReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RefreshTokenReqMultiError, or nil if none found.
func (m *RefreshTokenReq) ValidateAll() error {
	return m.validate(true)
}

func (m *RefreshTokenReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRefreshToken()) < 1 {
		err := RefreshTokenReqValidationError{
			field:  "RefreshToken",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RefreshTokenReqMultiError(errors)
	}

	return nil
}

// RefreshTokenReqMultiError is an error wrapping multiple validation errors
// returned by RefreshTokenReq.ValidateAll() if the designated constraints
// aren't met.
type RefreshTokenReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefreshTokenReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefreshTokenReqMultiError) AllErrors() []error { return m }

// RefreshTokenReqValidationError is the validation error returned by
// RefreshTokenReq.Validate if the designated constraints aren't met.
type RefreshTokenReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefreshTokenReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefreshTokenReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefreshTokenReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefreshTokenReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefreshTokenReqValidationError) ErrorName() string { return "RefreshTokenReqValidationError" }

// Error satisfies the builtin error interface
func (e RefreshTokenReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefreshTokenReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefreshTokenReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefreshTokenReqValidationError{}

// Validate checks the field values on RevokeTokenReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RevokeTokenReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevokeTokenReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RevokeTokenReqMultiError,
// or nil if none found.
func (m *RevokeTokenReq) ValidateAll() error {
	return m.validate(true)
}

func (m *RevokeTokenReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := RevokeTokenReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RevokeTokenReqMultiError(errors)
	}

	return nil
}

// RevokeTokenReqMultiError is an error wrapping multiple validation errors
// returned by RevokeTokenReq.ValidateAll() if the designated constraints
// aren't met.
type RevokeTokenReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevokeTokenReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevokeTokenReqMultiError) AllErrors() []error { return m }

// RevokeTokenReqValidationError is the validation error returned by
// RevokeTokenReq.Validate if the designated constraints aren't met.
type RevokeTokenReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevokeTokenReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevokeTokenReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevokeTokenReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevokeTokenReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevokeTokenReqValidationError) ErrorName() string { return "RevokeTokenReqValidationError" }

// Error satisfies the builtin error interface
func (e RevokeTokenReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevokeTokenReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevokeTokenReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevokeTokenReqValidationError{}

// Validate checks the field values on AddToBlacklistReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddToBlacklistReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddToBlacklistReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddToBlacklistReqMultiError, or nil if none found.
func (m *AddToBlacklistReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AddToBlacklistReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := AddToBlacklistReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for TtlSeconds

	if len(errors) > 0 {
		return AddToBlacklistReqMultiError(errors)
	}

	return nil
}

// AddToBlacklistReqMultiError is an error wrapping multiple validation errors
// returned by AddToBlacklistReq.ValidateAll() if the designated constraints
// aren't met.
type AddToBlacklistReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddToBlacklistReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddToBlacklistReqMultiError) AllErrors() []error { return m }

// AddToBlacklistReqValidationError is the validation error returned by
// AddToBlacklistReq.Validate if the designated constraints aren't met.
type AddToBlacklistReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddToBlacklistReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddToBlacklistReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddToBlacklistReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddToBlacklistReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddToBlacklistReqValidationError) ErrorName() string {
	return "AddToBlacklistReqValidationError"
}

// Error satisfies the builtin error interface
func (e AddToBlacklistReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddToBlacklistReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddToBlacklistReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddToBlacklistReqValidationError{}

// Validate checks the field values on CheckBlacklistReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CheckBlacklistReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckBlacklistReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckBlacklistReqMultiError, or nil if none found.
func (m *CheckBlacklistReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckBlacklistReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := CheckBlacklistReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CheckBlacklistReqMultiError(errors)
	}

	return nil
}

// CheckBlacklistReqMultiError is an error wrapping multiple validation errors
// returned by CheckBlacklistReq.ValidateAll() if the designated constraints
// aren't met.
type CheckBlacklistReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckBlacklistReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckBlacklistReqMultiError) AllErrors() []error { return m }

// CheckBlacklistReqValidationError is the validation error returned by
// CheckBlacklistReq.Validate if the designated constraints aren't met.
type CheckBlacklistReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckBlacklistReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckBlacklistReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckBlacklistReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckBlacklistReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckBlacklistReqValidationError) ErrorName() string {
	return "CheckBlacklistReqValidationError"
}

// Error satisfies the builtin error interface
func (e CheckBlacklistReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckBlacklistReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckBlacklistReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckBlacklistReqValidationError{}

// Validate checks the field values on CheckBlacklistReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckBlacklistReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckBlacklistReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckBlacklistReplyMultiError, or nil if none found.
func (m *CheckBlacklistReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckBlacklistReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsBlacklisted

	if len(errors) > 0 {
		return CheckBlacklistReplyMultiError(errors)
	}

	return nil
}

// CheckBlacklistReplyMultiError is an error wrapping multiple validation
// errors returned by CheckBlacklistReply.ValidateAll() if the designated
// constraints aren't met.
type CheckBlacklistReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckBlacklistReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckBlacklistReplyMultiError) AllErrors() []error { return m }

// CheckBlacklistReplyValidationError is the validation error returned by
// CheckBlacklistReply.Validate if the designated constraints aren't met.
type CheckBlacklistReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckBlacklistReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckBlacklistReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckBlacklistReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckBlacklistReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckBlacklistReplyValidationError) ErrorName() string {
	return "CheckBlacklistReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CheckBlacklistReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckBlacklistReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckBlacklistReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckBlacklistReplyValidationError{}
