// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: service/userauth/v1/user_auth.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 验证码消息 ==========
type CaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	PicPath       string                 `protobuf:"bytes,2,opt,name=pic_path,json=picPath,proto3" json:"pic_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaReply) Reset() {
	*x = CaptchaReply{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaReply) ProtoMessage() {}

func (x *CaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaReply.ProtoReflect.Descriptor instead.
func (*CaptchaReply) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CaptchaReply) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *CaptchaReply) GetPicPath() string {
	if x != nil {
		return x.PicPath
	}
	return ""
}

type VerifyCaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	Captcha       string                 `protobuf:"bytes,2,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaReq) Reset() {
	*x = VerifyCaptchaReq{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaReq) ProtoMessage() {}

func (x *VerifyCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaReq.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaReq) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyCaptchaReq) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *VerifyCaptchaReq) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type VerifyCaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaReply) Reset() {
	*x = VerifyCaptchaReply{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaReply) ProtoMessage() {}

func (x *VerifyCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaReply.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaReply) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCaptchaReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ========== 短信消息 ==========
type SendSmsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsReq) Reset() {
	*x = SendSmsReq{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsReq) ProtoMessage() {}

func (x *SendSmsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsReq.ProtoReflect.Descriptor instead.
func (*SendSmsReq) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SendSmsReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type SendSmsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsReply) Reset() {
	*x = SendSmsReply{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsReply) ProtoMessage() {}

func (x *SendSmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsReply.ProtoReflect.Descriptor instead.
func (*SendSmsReply) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SendSmsReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifySmsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SmsCode       string                 `protobuf:"bytes,2,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySmsReq) Reset() {
	*x = VerifySmsReq{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySmsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySmsReq) ProtoMessage() {}

func (x *VerifySmsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySmsReq.ProtoReflect.Descriptor instead.
func (*VerifySmsReq) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifySmsReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *VerifySmsReq) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

type VerifySmsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySmsReply) Reset() {
	*x = VerifySmsReply{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySmsReply) ProtoMessage() {}

func (x *VerifySmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySmsReply.ProtoReflect.Descriptor instead.
func (*VerifySmsReply) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{6}
}

func (x *VerifySmsReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ========== Token 消息 ==========
type IssueTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenReq) Reset() {
	*x = IssueTokenReq{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenReq) ProtoMessage() {}

func (x *IssueTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenReq.ProtoReflect.Descriptor instead.
func (*IssueTokenReq) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{7}
}

func (x *IssueTokenReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IssueTokenReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *IssueTokenReq) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type TokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiredAt     int64                  `protobuf:"varint,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // Access Token 过期时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenReply) Reset() {
	*x = TokenReply{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenReply) ProtoMessage() {}

func (x *TokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenReply.ProtoReflect.Descriptor instead.
func (*TokenReply) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{8}
}

func (x *TokenReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenReply) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RevokeTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenReq) Reset() {
	*x = RevokeTokenReq{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenReq) ProtoMessage() {}

func (x *RevokeTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenReq.ProtoReflect.Descriptor instead.
func (*RevokeTokenReq) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeTokenReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// ========== 黑名单消息 ==========
type AddToBlacklistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 黑名单 TTL（秒），0 表示使用默认值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToBlacklistReq) Reset() {
	*x = AddToBlacklistReq{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToBlacklistReq) ProtoMessage() {}

func (x *AddToBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToBlacklistReq.ProtoReflect.Descriptor instead.
func (*AddToBlacklistReq) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{11}
}

func (x *AddToBlacklistReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddToBlacklistReq) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CheckBlacklistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBlacklistReq) Reset() {
	*x = CheckBlacklistReq{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBlacklistReq) ProtoMessage() {}

func (x *CheckBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBlacklistReq.ProtoReflect.Descriptor instead.
func (*CheckBlacklistReq) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{12}
}

func (x *CheckBlacklistReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckBlacklistReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBlacklisted bool                   `protobuf:"varint,1,opt,name=is_blacklisted,json=isBlacklisted,proto3" json:"is_blacklisted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBlacklistReply) Reset() {
	*x = CheckBlacklistReply{}
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBlacklistReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBlacklistReply) ProtoMessage() {}

func (x *CheckBlacklistReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_userauth_v1_user_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBlacklistReply.ProtoReflect.Descriptor instead.
func (*CheckBlacklistReply) Descriptor() ([]byte, []int) {
	return file_service_userauth_v1_user_auth_proto_rawDescGZIP(), []int{13}
}

func (x *CheckBlacklistReply) GetIsBlacklisted() bool {
	if x != nil {
		return x.IsBlacklisted
	}
	return false
}

var File_service_userauth_v1_user_auth_proto protoreflect.FileDescriptor

const file_service_userauth_v1_user_auth_proto_rawDesc = "" +
	"\n" +
	"#service/userauth/v1/user_auth.proto\x12\x12lushop.userauth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"H\n" +
	"\fCaptchaReply\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x01 \x01(\tR\tcaptchaId\x12\x19\n" +
	"\bpic_path\x18\x02 \x01(\tR\apicPath\"]\n" +
	"\x10VerifyCaptchaReq\x12&\n" +
	"\n" +
	"captcha_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tcaptchaId\x12!\n" +
	"\acaptcha\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\acaptcha\".\n" +
	"\x12VerifyCaptchaReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\n" +
	"SendSmsReq\x12 \n" +
	"\x06mobile\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\vR\x06mobile\"(\n" +
	"\fSendSmsReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\fVerifySmsReq\x12 \n" +
	"\x06mobile\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\vR\x06mobile\x12$\n" +
	"\bsms_code\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x06\x18\x06R\asmsCode\"*\n" +
	"\x0eVerifySmsReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"b\n" +
	"\rIssueTokenReq\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x1b\n" +
	"\tnick_name\x18\x02 \x01(\tR\bnickName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\"s\n" +
	"\n" +
	"TokenReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\x03R\texpiredAt\"?\n" +
	"\x0fRefreshTokenReq\x12,\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\frefreshToken\"2\n" +
	"\x0eRevokeTokenReq\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\"V\n" +
	"\x11AddToBlacklistReq\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"5\n" +
	"\x11CheckBlacklistReq\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\"<\n" +
	"\x13CheckBlacklistReply\x12%\n" +
	"\x0eis_blacklisted\x18\x01 \x01(\bR\risBlacklisted2\xa7\a\n" +
	"\bUserAuth\x12d\n" +
	"\n" +
	"GetCaptcha\x12\x16.google.protobuf.Empty\x1a .lushop.userauth.v1.CaptchaReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/userauth/v1/captcha\x12]\n" +
	"\rVerifyCaptcha\x12$.lushop.userauth.v1.VerifyCaptchaReq\x1a&.lushop.userauth.v1.VerifyCaptchaReply\x12m\n" +
	"\aSendSms\x12\x1e.lushop.userauth.v1.SendSmsReq\x1a .lushop.userauth.v1.SendSmsReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/userauth/v1/sms/send\x12Q\n" +
	"\tVerifySms\x12 .lushop.userauth.v1.VerifySmsReq\x1a\".lushop.userauth.v1.VerifySmsReply\x12t\n" +
	"\n" +
	"IssueToken\x12!.lushop.userauth.v1.IssueTokenReq\x1a\x1e.lushop.userauth.v1.TokenReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/userauth/v1/token/issue\x12z\n" +
	"\fRefreshToken\x12#.lushop.userauth.v1.RefreshTokenReq\x1a\x1e.lushop.userauth.v1.TokenReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/userauth/v1/token/refresh\x12o\n" +
	"\vRevokeToken\x12\".lushop.userauth.v1.RevokeTokenReq\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/userauth/v1/token/revoke\x12O\n" +
	"\x0eAddToBlacklist\x12%.lushop.userauth.v1.AddToBlacklistReq\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\x0eCheckBlacklist\x12%.lushop.userauth.v1.CheckBlacklistReq\x1a'.lushop.userauth.v1.CheckBlacklistReplyB\x1bZ\x19lushop/api/userauth/v1;v1b\x06proto3"

var (
	file_service_userauth_v1_user_auth_proto_rawDescOnce sync.Once
	file_service_userauth_v1_user_auth_proto_rawDescData []byte
)

func file_service_userauth_v1_user_auth_proto_rawDescGZIP() []byte {
	file_service_userauth_v1_user_auth_proto_rawDescOnce.Do(func() {
		file_service_userauth_v1_user_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_userauth_v1_user_auth_proto_rawDesc), len(file_service_userauth_v1_user_auth_proto_rawDesc)))
	})
	return file_service_userauth_v1_user_auth_proto_rawDescData
}

var file_service_userauth_v1_user_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_service_userauth_v1_user_auth_proto_goTypes = []any{
	(*CaptchaReply)(nil),        // 0: lushop.userauth.v1.CaptchaReply
	(*VerifyCaptchaReq)(nil),    // 1: lushop.userauth.v1.VerifyCaptchaReq
	(*VerifyCaptchaReply)(nil),  // 2: lushop.userauth.v1.VerifyCaptchaReply
	(*SendSmsReq)(nil),          // 3: lushop.userauth.v1.SendSmsReq
	(*SendSmsReply)(nil),        // 4: lushop.userauth.v1.SendSmsReply
	(*VerifySmsReq)(nil),        // 5: lushop.userauth.v1.VerifySmsReq
	(*VerifySmsReply)(nil),      // 6: lushop.userauth.v1.VerifySmsReply
	(*IssueTokenReq)(nil),       // 7: lushop.userauth.v1.IssueTokenReq
	(*TokenReply)(nil),          // 8: lushop.userauth.v1.TokenReply
	(*RefreshTokenReq)(nil),     // 9: lushop.userauth.v1.RefreshTokenReq
	(*RevokeTokenReq)(nil),      // 10: lushop.userauth.v1.RevokeTokenReq
	(*AddToBlacklistReq)(nil),   // 11: lushop.userauth.v1.AddToBlacklistReq
	(*CheckBlacklistReq)(nil),   // 12: lushop.userauth.v1.CheckBlacklistReq
	(*CheckBlacklistReply)(nil), // 13: lushop.userauth.v1.CheckBlacklistReply
	(*emptypb.Empty)(nil),       // 14: google.protobuf.Empty
}
var file_service_userauth_v1_user_auth_proto_depIdxs = []int32{
	14, // 0: lushop.userauth.v1.UserAuth.GetCaptcha:input_type -> google.protobuf.Empty
	1,  // 1: lushop.userauth.v1.UserAuth.VerifyCaptcha:input_type -> lushop.userauth.v1.VerifyCaptchaReq
	3,  // 2: lushop.userauth.v1.UserAuth.SendSms:input_type -> lushop.userauth.v1.SendSmsReq
	5,  // 3: lushop.userauth.v1.UserAuth.VerifySms:input_type -> lushop.userauth.v1.VerifySmsReq
	7,  // 4: lushop.userauth.v1.UserAuth.IssueToken:input_type -> lushop.userauth.v1.IssueTokenReq
	9,  // 5: lushop.userauth.v1.UserAuth.RefreshToken:input_type -> lushop.userauth.v1.RefreshTokenReq
	10, // 6: lushop.userauth.v1.UserAuth.RevokeToken:input_type -> lushop.userauth.v1.RevokeTokenReq
	11, // 7: lushop.userauth.v1.UserAuth.AddToBlacklist:input_type -> lushop.userauth.v1.AddToBlacklistReq
	12, // 8: lushop.userauth.v1.UserAuth.CheckBlacklist:input_type -> lushop.userauth.v1.CheckBlacklistReq
	0,  // 9: lushop.userauth.v1.UserAuth.GetCaptcha:output_type -> lushop.userauth.v1.CaptchaReply
	2,  // 10: lushop.userauth.v1.UserAuth.VerifyCaptcha:output_type -> lushop.userauth.v1.VerifyCaptchaReply
	4,  // 11: lushop.userauth.v1.UserAuth.SendSms:output_type -> lushop.userauth.v1.SendSmsReply
	6,  // 12: lushop.userauth.v1.UserAuth.VerifySms:output_type -> lushop.userauth.v1.VerifySmsReply
	8,  // 13: lushop.userauth.v1.UserAuth.IssueToken:output_type -> lushop.userauth.v1.TokenReply
	8,  // 14: lushop.userauth.v1.UserAuth.RefreshToken:output_type -> lushop.userauth.v1.TokenReply
	14, // 15: lushop.userauth.v1.UserAuth.RevokeToken:output_type -> google.protobuf.Empty
	14, // 16: lushop.userauth.v1.UserAuth.AddToBlacklist:output_type -> google.protobuf.Empty
	13, // 17: lushop.userauth.v1.UserAuth.CheckBlacklist:output_type -> lushop.userauth.v1.CheckBlacklistReply
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_userauth_v1_user_auth_proto_init() }
func file_service_userauth_v1_user_auth_proto_init() {
	if File_service_userauth_v1_user_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_userauth_v1_user_auth_proto_rawDesc), len(file_service_userauth_v1_user_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_userauth_v1_user_auth_proto_goTypes,
		DependencyIndexes: file_service_userauth_v1_user_auth_proto_depIdxs,
		MessageInfos:      file_service_userauth_v1_user_auth_proto_msgTypes,
	}.Build()
	File_service_userauth_v1_user_auth_proto = out.File
	file_service_userauth_v1_user_auth_proto_goTypes = nil
	file_service_userauth_v1_user_auth_proto_depIdxs = nil
}
