# server:
#   grpc:
#     addr: 0.0.0.0:50051
#     timeout: 1s
# service:
#   name: "user.service"
# data:
#   database:
#     driver: mysql
#     source: root:123456@tcp(127.0.0.1:3306)/lushop_user?charset=utf8mb4&parseTime=True&loc=Local
#   redis:
#     addr: 127.0.0.1:6379
#     dial_timeout: 1s
#     read_timeout: 0.2s
#     write_timeout: 0.2s
# trace:
#   endpoint: http://127.0.0.1:14268/api/traces
nacos:
  addr: 127.0.0.1
  port: 8848
  namespaceId: de9c6a0e-1fbc-425d-8d3b-09066fea6889
  dataId: user.yaml
  groupId: lushop_grpc
