// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: service/inventory/v1/inventory.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GoodsInvInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GoodsInvInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GoodsInvInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GoodsInvInfoMultiError, or
// nil if none found.
func (m *GoodsInvInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *GoodsInvInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GoodsId

	// no validation rules for Num

	if len(errors) > 0 {
		return GoodsInvInfoMultiError(errors)
	}

	return nil
}

// GoodsInvInfoMultiError is an error wrapping multiple validation errors
// returned by GoodsInvInfo.ValidateAll() if the designated constraints aren't met.
type GoodsInvInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GoodsInvInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GoodsInvInfoMultiError) AllErrors() []error { return m }

// GoodsInvInfoValidationError is the validation error returned by
// GoodsInvInfo.Validate if the designated constraints aren't met.
type GoodsInvInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GoodsInvInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GoodsInvInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GoodsInvInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GoodsInvInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GoodsInvInfoValidationError) ErrorName() string { return "GoodsInvInfoValidationError" }

// Error satisfies the builtin error interface
func (e GoodsInvInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGoodsInvInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GoodsInvInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GoodsInvInfoValidationError{}

// Validate checks the field values on SellInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SellInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SellInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SellInfoMultiError, or nil
// if none found.
func (m *SellInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SellInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetGoodsInfo() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SellInfoValidationError{
						field:  fmt.Sprintf("GoodsInfo[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SellInfoValidationError{
						field:  fmt.Sprintf("GoodsInfo[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SellInfoValidationError{
					field:  fmt.Sprintf("GoodsInfo[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for OrderSn

	if len(errors) > 0 {
		return SellInfoMultiError(errors)
	}

	return nil
}

// SellInfoMultiError is an error wrapping multiple validation errors returned
// by SellInfo.ValidateAll() if the designated constraints aren't met.
type SellInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SellInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SellInfoMultiError) AllErrors() []error { return m }

// SellInfoValidationError is the validation error returned by
// SellInfo.Validate if the designated constraints aren't met.
type SellInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SellInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SellInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SellInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SellInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SellInfoValidationError) ErrorName() string { return "SellInfoValidationError" }

// Error satisfies the builtin error interface
func (e SellInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSellInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SellInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SellInfoValidationError{}
