// Code generated by MockGen. DO NOT EDIT.
// Source: userop/internal/biz (interfaces: FavoriteRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "userop/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockFavoriteRepo is a mock of FavoriteRepo interface.
type MockFavoriteRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFavoriteRepoMockRecorder
}

// MockFavoriteRepoMockRecorder is the mock recorder for MockFavoriteRepo.
type MockFavoriteRepoMockRecorder struct {
	mock *MockFavoriteRepo
}

// NewMockFavoriteRepo creates a new mock instance.
func NewMockFavoriteRepo(ctrl *gomock.Controller) *MockFavoriteRepo {
	mock := &MockFavoriteRepo{ctrl: ctrl}
	mock.recorder = &MockFavoriteRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavoriteRepo) EXPECT() *MockFavoriteRepoMockRecorder {
	return m.recorder
}

// AddUserFav mocks base method.
func (m *MockFavoriteRepo) AddUserFav(arg0 context.Context, arg1 domain.Favorite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserFav", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserFav indicates an expected call of AddUserFav.
func (mr *MockFavoriteRepoMockRecorder) AddUserFav(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserFav", reflect.TypeOf((*MockFavoriteRepo)(nil).AddUserFav), arg0, arg1)
}

// DeleteUserFav mocks base method.
func (m *MockFavoriteRepo) DeleteUserFav(arg0 context.Context, arg1 domain.Favorite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserFav", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserFav indicates an expected call of DeleteUserFav.
func (mr *MockFavoriteRepoMockRecorder) DeleteUserFav(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserFav", reflect.TypeOf((*MockFavoriteRepo)(nil).DeleteUserFav), arg0, arg1)
}

// GetFavList mocks base method.
func (m *MockFavoriteRepo) GetFavList(arg0 context.Context, arg1 domain.Favorite) (*domain.UserFavListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavList", arg0, arg1)
	ret0, _ := ret[0].(*domain.UserFavListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavList indicates an expected call of GetFavList.
func (mr *MockFavoriteRepoMockRecorder) GetFavList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavList", reflect.TypeOf((*MockFavoriteRepo)(nil).GetFavList), arg0, arg1)
}

// GetUserFavDetail mocks base method.
func (m *MockFavoriteRepo) GetUserFavDetail(arg0 context.Context, arg1 domain.Favorite) (*domain.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFavDetail", arg0, arg1)
	ret0, _ := ret[0].(*domain.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFavDetail indicates an expected call of GetUserFavDetail.
func (mr *MockFavoriteRepoMockRecorder) GetUserFavDetail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFavDetail", reflect.TypeOf((*MockFavoriteRepo)(nil).GetUserFavDetail), arg0, arg1)
}
